---
title: "Wallace Lab Git Workshop"
author: "Flic Anderson & Sam Haynes"
date: "26/11/2020"
output:
  ioslides_presentation:
    logo: https://assets.stickpng.com/images/5847f981cef1014c0b5e48be.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script>
    $(document).ready(function() {
      $('slide:not(.title-slide, .backdrop, .segue)').append('<footer label=\"bit.ly/wallace-lab-git\"></footer>');    
    })
</script>

<style>
  footer:after {
    content: attr(label);
    font-size: 12pt;
    position: absolute;
    bottom: 20px;
    left: 100px;
    line-height: 1.9;
  }
</style>

## HOW TO (RE-)USE THIS MATERIAL

This is a `.html` presentation created in `R Markdown` with `ioslides`. 

(It's been written in a [.Rmd](http://rmarkdown.rstudio.com) file, and we generated .html slides by 'knitting' it in Rstudio.)

You can check out the code used to make these slides at the [Workshop repo](https://github.com/FlicAnderson/20201127-gitflow-workshop) on Github, and adapt it for your own presentations if you like - we've got a MIT Licence on the repo, which means: 

*"Basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source."*

Source: [tl;drLegal](https://tldrlegal.com/license/mit-license)

## TODO SAM: 

- [x] SAM: will message the lab about 'favourite paper' & 1-line summaries of how it's informed/related to your work 

<div class="red2">
- [ ] SAM: Slides about branching
- [ ] SAM: Slides about paper workflow
- [ ] SAM: Slides about troubleshooting
</div>

## TODO FLIC: 

- [x] FLIC: set up repo & slide deck 
- [x] FLIC: send Sam the notes from this meeting. 
- [x] FLIC: make & send out pre-workshop info to folks by Thursday morning (19th). 
- [x] FLIC: set up a pre-workshop drop-in for after setup info sent out
- [x] FLIC: make blogpost on my fork of lab website for workshop
- [x] FLIC: slides about intro

<div class="red2">
- [ ] FLIC: slides about task
- [ ] FLIC: slides about workflow
- [ ] FLIC: slides about issue tickets
</div>

# Outline: 

## Outline: 

* 15 min - Intro to Git, GitHub & The Git Workflow (FLIC) 
* 10-15 min - Favourite Papers Lab Website Task (FLIC) 
* 10 min - Issue Tickets, Bells & Whistles (FLIC) 
* 10 min - Branching & Writing Papers (SAM) 
* 10 min - Troubleshooting: (SAM) 
* Questions

## Outline: 

* Intro to Git, GitHub  (FLIC) 
* The Git Workflow (FLIC) 
* Favourite Papers Lab Website Task (FLIC) 
* Issue Tickets, Bells & Whistles (FLIC) 
* Branching 
* Writing Papers (SAM) 
* Troubleshooting: (SAM) 
* Questions

# Intro:

## Git

**Git** is a *version control system*. 

* It doesn't copy your files, as much as keep track of all `changes` ever since you told git to `add` the file to its logs
* Best for `text` files; can't see 'into' binaries (e.g. pdfs, pics)
* Saves the changes you tell it to `commit` to its log in project-specific folders referred to as a repository, or `repo`
* Very useful: undo/redo, backups, switching computers, safely 'experimenting'

It can be used via *Command Line* (the terminal!) or via a *Graphical User Interface* (GUI), on pretty much all systems.

## GitHub

**GitHub** is an *online platform* for storing your git repository. There are others (e.g. GitLab, Bitbucket).

* Keep track of all your repos online - `public` or `private`
* You can tell git to `push` its list of your file changes up to GitHub.
* Or `pull` changes down (yours or someone else's!) and `merge` them with your local copies. 
* Contribute to others' work via a `pull request` 

## Git Workflow

Include a picture

## How To Write A Good Commit Message

git commit -m "..."

## How/When To Pull Request

Fork, Clone, Branch, Edit, Add, Commit, Push, Pull Request

## Favourite Papers Task

**Task:** "Add your favourite paper & 1-line summary to a blog post on the lab website"

**Aim:** practise the basics of fork/branch/change/PR et & make an interesting blog post!

The [Wallace lab website](https://ewallace.github.io/) is built from a github repository, and uses [GitHub Pages](https://pages.github.com/) to build the website HTML/CSS from the files in a GitHub repository & hosts them online.

Our task is to add favourite-paper info to the blog post file using the git workflow so we can publish it to the website.

## Flic's Task Setup | *Fork, Clone, Branch, Edit, Add, Commit, Push, Pull Request*

* `forked` (made a copy of) Edward's website repo on GitHub 
* `cloned` the forked repository (downloaded the github copy to her local computer)
* made a `branch` for her changes called "workshop-blogpost"
* created and `edited` a blog post file: "blog/_posts/2020-11-26-favourite-papers.md"
* `added` this file to her 'staging area' locally
* written a `commit` message to explain her changes
* `pushed` her changes up to her copy of the repo on GitHub
* (no `pull request` yet, we're ready to collaborate!)

## Favourite Papers Steps | *Fork, Clone, Branch, Edit, Add, Commit, Push, Pull Request*

* fork my fork in github (it copies all branches)
* make branch (e.g."sams-favourite-paper")
* make edits to "blog/_posts/2020-11-26-favourite-papers.md"
* git add blog file
* git commit blog file with helpful message
* git push to their github (to remote)
* check on github the changes are there
* make pull request to my fork (check the branch)

## Favourite Papers Next Steps | *Pull Request & Merge*

I accept them, merge them, we party

I submit pull request to Edward's original repo staging branch

Edward checks the blog post & merges the changes to `master` branch
 ...publishing the blogpost!

## Issue Tickets 

* 10min issue tickets & tagging them & stuff (FLIC) 
  - slide with "when to make an issue ticket?"
  - " 1 ticket, or two?" - how to decide where 1 issue stops and another begins?
  - tagging folks in
  - labels
  - ?'kanban'? <- probably a step too far, ignore this!

## Branching & Forks

* 10min branching! tying into how the lab website works (SAM) 
  - how & why to do branches
  - how & why to check which branch you're in
  - why does the lab website have a 'staging' branch? what's this master branch thing all about? 
  - why do we fork the website?
  - issue-focussed branches (e.g. if issue created in task)
  - + 1 slide on how to workflow for a paper (Sam & Jamie's experiences)

## Troubleshooting

* last 10 mins or so: troubleshooting: (SAM) 
  - what to do if it goes wrong? (can skip talking about some of this if we run out of time but want it on slides at least)
  - what if you're working in the wrong branch??!?
  - what to do if you want to push fewer changes than you committed?
  - how to revert if things go wrong? 
  - git cherrypicking?
  - use of git stash
  - here's some additional resources
  ? Recorded walkthrough of here are some useful commands 

## Questions

* (any time left?) Questions?
  - if any additional practical Qs, could set up a work-through-it time?
  - if any conceptual questions etc, try and answer in time left.
